-- MySQL Script generated by MySQL Workbench
-- Tue Apr 27 20:56:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VTS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VTS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VTS` DEFAULT CHARACTER SET utf8 ;
USE `VTS` ;

-- -----------------------------------------------------
-- Table `VTS`.`Kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Kategorie` (
  `Kategorie_ID` INT NOT NULL,
  `Bezeichnung` VARCHAR(45) NULL,
  PRIMARY KEY (`Kategorie_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VTS`.`Artikel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Artikel` (
  `Artikel_ID` INT NOT NULL,
  `Artikelname` VARCHAR(45) NOT NULL,
  `Mehrwertsteuer` VARCHAR(45) NULL,
  `BildNr` INT NULL,
  `Kategorie_ID` INT NOT NULL,
  PRIMARY KEY (`Artikel_ID`),
  INDEX `fk_Artikel_Kategorie1_idx` (`Kategorie_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Artikel_Kategorie1`
    FOREIGN KEY (`Kategorie_ID`)
    REFERENCES `VTS`.`Kategorie` (`Kategorie_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VTS`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Adresse` (
  `Adresse_ID` INT NOT NULL,
  `Straße` VARCHAR(45) NULL,
  `PLZ` INT NULL,
  `Stadt` VARCHAR(45) NULL,
  `Stadtteil` VARCHAR(45) NULL,
  `Bundesland` VARCHAR(45) NULL,
  `Land` VARCHAR(45) NULL,
  PRIMARY KEY (`Adresse_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VTS`.`Kundentyp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Kundentyp` (
  `Kundentyp_ID` INT NOT NULL,
  `Bezeichung` VARCHAR(45) NULL,
  PRIMARY KEY (`Kundentyp_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VTS`.`Kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Kunde` (
  `Kunde_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Vorname` VARCHAR(45) NULL,
  `Telefon` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Passwort` VARCHAR(255) NULL,
  `Adresse_ID` INT NOT NULL,
  `Kundentyp_ID` INT NOT NULL,
  PRIMARY KEY (`Kunde_ID`),
  INDEX `Adresse_ID_idx` (`Adresse_ID` ASC) VISIBLE,
  INDEX `fk_Kunde_Kundentyp1_idx` (`Kundentyp_ID` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `Adresse_ID`
    FOREIGN KEY (`Adresse_ID`)
    REFERENCES `VTS`.`Adresse` (`Adresse_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kunde_Kundentyp1`
    FOREIGN KEY (`Kundentyp_ID`)
    REFERENCES `VTS`.`Kundentyp` (`Kundentyp_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VTS`.`Bezahlmethode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Bezahlmethode` (
  `Bezahlmethode_ID` INT NOT NULL,
  `Bezeichnung` VARCHAR(45) NULL,
  PRIMARY KEY (`Bezahlmethode_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VTS`.`Bestellung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Bestellung` (
  `Bestellung_ID` INT NOT NULL,
  `Bestelldatum` TIMESTAMP(6) NOT NULL,
  `Versanddatum` TIMESTAMP(6) NULL,
  `Lieferkosten` DECIMAL(2) NULL,
  `Kunde_ID` INT NOT NULL,
  `Lieferdresse_ID` INT NOT NULL,
  `Bezahlmethode_ID` INT NOT NULL,
  `Rechnungsadresse_ID` INT NOT NULL,
  PRIMARY KEY (`Bestellung_ID`),
  INDEX `Kunde_ID_idx` (`Kunde_ID` ASC) VISIBLE,
  INDEX `Lieferadresse_ID_idx` (`Lieferdresse_ID` ASC) VISIBLE,
  INDEX `fk_Bestellung_Bezahlmethode1_idx` (`Bezahlmethode_ID` ASC) VISIBLE,
  INDEX `fk_Bestellung_Adresse1_idx` (`Rechnungsadresse_ID` ASC) VISIBLE,
  CONSTRAINT `Kunde_ID`
    FOREIGN KEY (`Kunde_ID`)
    REFERENCES `VTS`.`Kunde` (`Kunde_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Lieferadresse_ID`
    FOREIGN KEY (`Lieferdresse_ID`)
    REFERENCES `VTS`.`Adresse` (`Adresse_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bestellung_Bezahlmethode1`
    FOREIGN KEY (`Bezahlmethode_ID`)
    REFERENCES `VTS`.`Bezahlmethode` (`Bezahlmethode_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bestellung_Adresse1`
    FOREIGN KEY (`Rechnungsadresse_ID`)
    REFERENCES `VTS`.`Adresse` (`Adresse_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VTS`.`Packung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Packung` (
  `Packung_ID` INT NOT NULL,
  `Packungsgroessee` INT NULL,
  `Verkaufspreis` DECIMAL(2) NULL,
  `Mindestbestand` INT NULL,
  `Lagermenge` INT NULL,
  `Artikel_ID` INT NOT NULL,
  PRIMARY KEY (`Packung_ID`),
  INDEX `fk_Packung_Artikel1_idx` (`Artikel_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Packung_Artikel1`
    FOREIGN KEY (`Artikel_ID`)
    REFERENCES `VTS`.`Artikel` (`Artikel_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VTS`.`Bestellungsposition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Bestellungsposition` (
  `Bestellungsposition_ID` INT NOT NULL,
  `Preis` DECIMAL(2) NULL,
  `Anzahl` INT NULL,
  `Bestellpositionsnummer` VARCHAR(45) NOT NULL,
  `Bestellung_ID` INT NOT NULL,
  `Packung_ID` INT NOT NULL,
  PRIMARY KEY (`Bestellungsposition_ID`),
  UNIQUE INDEX `Bestellpositionsnummer_UNIQUE` (`Bestellpositionsnummer` ASC) VISIBLE,
  INDEX `fk_Bestellungsposition_Bestellung1_idx` (`Bestellung_ID` ASC) VISIBLE,
  INDEX `fk_Bestellungsposition_Packung1_idx` (`Packung_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Bestellungsposition_Bestellung1`
    FOREIGN KEY (`Bestellung_ID`)
    REFERENCES `VTS`.`Bestellung` (`Bestellung_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bestellungsposition_Packung1`
    FOREIGN KEY (`Packung_ID`)
    REFERENCES `VTS`.`Packung` (`Packung_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VTS`.`Bestellfaehigkeit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Bestellfaehigkeit` (
  `Bestellfaehigkeit_ID` INT NOT NULL,
  `Kundentyp_ID` INT NOT NULL,
  `Kategorie_ID` INT NOT NULL,
  PRIMARY KEY (`Bestellfaehigkeit_ID`),
  INDEX `fk_Bestellfaehigkeit_Kundentyp1_idx` (`Kundentyp_ID` ASC) VISIBLE,
  INDEX `fk_Bestellfaehigkeit_Kategorie1_idx` (`Kategorie_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Bestellfaehigkeit_Kundentyp1`
    FOREIGN KEY (`Kundentyp_ID`)
    REFERENCES `VTS`.`Kundentyp` (`Kundentyp_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bestellfaehigkeit_Kategorie1`
    FOREIGN KEY (`Kategorie_ID`)
    REFERENCES `VTS`.`Kategorie` (`Kategorie_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VTS`.`Lieferant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Lieferant` (
  `Lieferant_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Adresse_ID` INT NOT NULL,
  PRIMARY KEY (`Lieferant_ID`),
  INDEX `fk_Lieferant_Adresse1_idx` (`Adresse_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Lieferant_Adresse1`
    FOREIGN KEY (`Adresse_ID`)
    REFERENCES `VTS`.`Adresse` (`Adresse_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VTS`.`Lieferfaehigkeit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VTS`.`Lieferfaehigkeit` (
  `Lieferfaehigkeit_ID` INT NOT NULL,
  `Preis` DECIMAL(2) NULL,
  `Versandkosten` DECIMAL(2) NULL,
  `Lieferant_ID` INT NOT NULL,
  `Packung_ID` INT NOT NULL,
  PRIMARY KEY (`Lieferfaehigkeit_ID`),
  INDEX `fk_Lieferfaehigkeit_Lieferant1_idx` (`Lieferant_ID` ASC) VISIBLE,
  INDEX `fk_Lieferfaehigkeit_Packung1_idx` (`Packung_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Lieferfaehigkeit_Lieferant1`
    FOREIGN KEY (`Lieferant_ID`)
    REFERENCES `VTS`.`Lieferant` (`Lieferant_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lieferfaehigkeit_Packung1`
    FOREIGN KEY (`Packung_ID`)
    REFERENCES `VTS`.`Packung` (`Packung_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
